### ISSUE TITLE
Migrate Project to SQLC for Type-Safe Database Operations

### ISSUE THREAD

**Issue by obrunogonzaga** [obrunogonzaga/go-template#3]
Currently, our project uses raw SQL queries with manual scanning. We should migrate to sqlc to generate type-safe Go code from SQL, reducing boilerplate and potential runtime errors.

## Current Implementation
```go
// Current manual implementation
func (r *userRepository) GetByID(ctx context.Context, id string) (*entity.User, error) {
    query := `SELECT id, name, email, created_at, updated_at FROM users WHERE id = $1`
    user := &entity.User{}
    err := r.db.QueryRowContext(ctx, query, id).Scan(
        &user.ID,
        &user.Name,
        &user.Email,
        &user.CreatedAt,
        &user.UpdatedAt,
    )
    // ... error handling
}
```

### 1. Project Setup

1. Install sqlc:
```bash
go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
```

2. Create sqlc configuration:
```yaml
# sqlc.yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "./internal/repository/queries/"
    schema: "./internal/repository/schema/"
    gen:
      go:
        package: "repository"
        out: "./internal/repository/sqlc"
        emit_json_tags: true
        emit_prepared_queries: true
        emit_interface: true
        emit_exact_table_names: false
        emit_empty_slices: true
```

### 2. Directory Structure
```
internal/
  └── repository/
      ├── queries/          # SQL query files
      │   └── users.sql
      ├── schema/           # Database schema
      │   └── schema.sql
      └── sqlc/            # Generated code
```

#### Schema (schema.sql):
```sql
CREATE TABLE users (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);
```

#### Queries (users.sql):
```sql
-- name: GetUser :one
SELECT * FROM users
WHERE id = $1 LIMIT 1;

-- name: ListUsers :many
SELECT * FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2;

-- name: CreateUser :exec
INSERT INTO users (
    id, name, email, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5
);

-- name: UpdateUser :exec
UPDATE users
SET name = $2,
    email = $3,
    updated_at = $4
WHERE id = $1;

-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1;

-- name: GetUserCount :one
SELECT COUNT(*) FROM users;
```

### 4. Repository Implementation

```go
// New repository structure using sqlc
type UserRepository struct {
    queries *repository.Queries
    db      *sql.DB
}

func NewUserRepository(db *sql.DB) *UserRepository {
    return &UserRepository{
        queries: repository.New(db),
        db:      db,
    }
}
```

## Implementation Steps

1. **Project Setup**:
   - Install sqlc
   - Create configuration file
   - Setup directory structure

2. **SQL Files**:
   - Create schema definitions
   - Write query files
   - Document query annotations

3. **Code Generation**:
   - Run sqlc generate
   - Review generated code
   - Update repository implementation

4. **Repository Migration**:
   - Update repository interface
   - Implement methods using generated code
   - Add transaction support

### Generated Interface
```go
type Querier interface {
    CreateUser(ctx context.Context, arg CreateUserParams) error
    DeleteUser(ctx context.Context, id string) error
    GetUser(ctx context.Context, id string) (User, error)
    ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
    UpdateUser(ctx context.Context, arg UpdateUserParams) error
}
```

### Repository Methods
```go
func (r *UserRepository) Create(ctx context.Context, user *entity.User) error {
    return r.queries.CreateUser(ctx, repository.CreateUserParams{
        ID:        user.ID,
        Name:      user.Name,
        Email:     user.Email,
        CreatedAt: user.CreatedAt,
        UpdatedAt: user.UpdatedAt,
    })
}
```

## Acceptance Criteria

- [ ] Install and configure sqlc
- [ ] Create SQL schema files
- [ ] Write SQL query files
- [ ] Generate Go code using sqlc
- [ ] Update repository implementation
- [ ] Add transaction support
- [ ] Update tests to use new implementation
- [ ] Document generated code usage
- [ ] Add migration guide
- [ ] Verify type safety
- [ ] Ensure performance metrics
- [ ] Update project documentation

## Technical Considerations

1. **Type Safety**:
   - Generated code provides compile-time type checking
   - No runtime scanning errors
   - Type-safe query parameters

2. **Performance**:
   - Prepared statements
   - Connection pooling
   - Query optimization

3. **Maintainability**:
   - Centralized SQL queries
   - Easy to review and modify
   - Version control for queries

4. **Migration**:
   - Backward compatibility
   - Zero downtime deployment
   - Rollback strategy

## Testing Strategy

1. **Unit Tests**:
   - Test generated code
   - Mock database interface
   - Transaction tests

2. **Integration Tests**:
   - Full database tests
   - Transaction isolation
   - Concurrent operations

## Documentation Updates

1. **README.md**:
   - Add sqlc setup instructions
   - Update development workflow
   - Document query conventions

2. **API Documentation**:
   - Update repository examples
   - Add transaction examples
   - Document error handling

## Migration Guide

1. Install sqlc
2. Configure project
3. Write SQL files
4. Generate code
5. Update repository
6. Update tests
7. Deploy changes

## Related
- Current repository implementation
- Database migrations
- Testing suite
- CI/CD pipeline

## Labels
- enhancement
- database
- refactor
- type-safety
- performance

## Estimated Complexity
Medium

## Priority
High

## Additional Resources
- [SQLC Documentation](https://sqlc.dev/)
- [Golang Database Best Practices](https://golang.org/doc/database/)
- [PostgreSQL Documentation](https://www.postgresql.org/docs/)

## Benefits
1. Type-safe database operations
2. Reduced boilerplate code
3. Better maintainability
4. Compile-time error checking
5. Improved developer experience
6. Better code organization
7. Easier testing
